---

galaxy_info:
  author: Christian Krause
  description: install and configure systemd-timesyncd
  company: German Centre for Integrative Biodiversity Research (iDiv)
  license: MIT
  min_ansible_version: '2.9'

  platforms:

    - name: ArchLinux
      versions:
        - all

    - name: Debian
      versions:
        - bookworm
        - bullseye

    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble

  galaxy_tags:
    - systemd
    - timesyncd

...
