---

argument_specs:
  main:
    options:

      systemd_networkd_networks:
        type: list
        elements: dict
        options:
          name:
            type: str
          match:
            type: dict
            options:
              name:
                type: str
          network:
            type: dict
            options:
              address:
                type: str
              dhcp:
                type: str
              dns:
                type: list
                elements: str
              domains:
                type: list
                elements: str
              gateway:
                type: str
              link_local_addressing:
                type: str
              llmnr:
                type: str
              multicast_dns:
                type: str
              ntp:
                type: list
                elements: str
          dhcp:
            type: dict
            options:
              route_metric:
                type: int

...
