---

- name: include OS-specific vars
  ansible.builtin.include_vars: >-
    {{ lookup("ansible.builtin.first_found", __systemd_timesyncd_vars_files) }}

- name: set time zone
  community.general.timezone:
    name: '{{ systemd_timesyncd_timezone }}'
  become: yes
  when:
    - systemd_timesyncd_timezone is defined
  tags:
    - timezone

# -----------------------------------------------------------------------------
# install
# -----------------------------------------------------------------------------

- name: remove legacy NTP clients
  ansible.builtin.package:
    name:
      - chrony
      - ntp
    state: absent
  become: yes
  when:
    - systemd_timesyncd_remove_legacy_packages

- name: 'install package {{ __systemd_timesyncd_package }}'
  ansible.builtin.package:
    name: '{{ __systemd_timesyncd_package }}'
    state: present
  become: yes
  tags:
    - install

# -----------------------------------------------------------------------------
# config
# -----------------------------------------------------------------------------

- name: create conf.d directory
  ansible.builtin.file:
    path: /etc/systemd/timesyncd.conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes
  tags:
    - config

- name: configure systemd-timesyncd
  ansible.builtin.template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf.d/60-ansible.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  register: __systemd_timesyncd_configuration
  tags:
    - config

# -----------------------------------------------------------------------------
# service
# -----------------------------------------------------------------------------

- name: start systemd-timesyncd service
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: >-
      {{
        __systemd_timesyncd_configuration.changed |
          default(False) |
          ternary("restarted", "started")
      }}
  become: yes
  when:
    # forbidden in service unit via `ConditionVirtualization=!container`
    - not (
        ansible_facts.virtualization_role == "guest"
        and
        ansible_facts.virtualization_type == "docker"
      )
  tags:
    - service

- name: enable systemd-timesyncd service
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: yes
  become: yes
  tags:
    - service

...
