---

dependency:
  name: galaxy

driver:
  name: docker

platforms:

  - name: archlinux
    image: carlodepieri/docker-archlinux-ansible:latest
    pre_build_image: yes
    privileged: yes
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd

  - name: debian-bullseye
    image: geerlingguy/docker-debian11-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: yes
    pre_build_image: yes

  - name: debian-bookworm
    image: geerlingguy/docker-debian12-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: yes
    pre_build_image: yes

  - name: rockylinux-9
    image: dokken/rockylinux-9
    pre_build_image: yes
    privileged: yes
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
    groups:
      - redhat

  - name: ubuntu-focal
    image: dokken/ubuntu-20.04
    pre_build_image: yes
    privileged: yes
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
    groups:
      - ubuntu

  - name: ubuntu-jammy
    image: dokken/ubuntu-22.04
    pre_build_image: yes
    privileged: yes
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
    groups:
      - ubuntu

  - name: ubuntu-noble
    image: dokken/ubuntu-24.04
    pre_build_image: yes
    privileged: yes
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
    groups:
      - ubuntu

provisioner:
  name: ansible
  inventory:
    host_vars:
      archlinux:
        ansible_user: ansible

verifier:
  name: ansible

...
