---

name: molecule-timesyncd

on:
  pull_request:
    paths:
      - .config/molecule
      - .github/workflows/molecule-timesyncd.yml
      - roles/systemd_timesyncd
  push:
    branches:
      - main
      - wip/next
    paths:
      - .config/molecule
      - .github/workflows/molecule-timesyncd.yml
      - roles/systemd_timesyncd

jobs:

  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - archlinux
          - debian-bullseye
          - debian-bookworm
          - ubuntu-focal
          - ubuntu-jammy
          - ubuntu-noble
        scenario:
          - default
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip3 install ansible molecule molecule-plugins[docker] docker
      - run: ansible --version
      - run: molecule --version
      - run: molecule test -p ${{ matrix.distro }} -s ${{ matrix.scenario }}
        working-directory: ./roles/systemd_timesyncd
        env:
          ANSIBLE_DIFF_ALWAYS: 'True'
          PY_COLORS: '1'

...
